name: SDXL Models Nightly

on:
  schedule:
    - cron:  '30 6 * * *'

jobs:
  test-sdxl-models:
    strategy:
      matrix:
        version: [3.11]
        os: [nodai-amdgpu-mi250-x86-64]

    runs-on: ${{matrix.os}}
    steps:
      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: ${{matrix.version}}

      - name: "Checkout Code"
        uses: actions/checkout@v4
        with:
          ref: ean-sd-fp16

      - name: "Checkout iree-turbine"
        uses: actions/checkout@v4
        with:
          repository: iree-org/iree-turbine
          # TODO: Let the ref be passed as a parameter to run integration tests.
          path: iree-turbine

      - name: Sync source deps
        # build IREE from source with -DIREE_BUILD_TRACY=ON if getting tracy profile
        run: |
          python -m pip install --upgrade pip
          # Note: We install in three steps in order to satisfy requirements
          # from non default locations first. Installing the PyTorch CPU
          # wheels saves multiple minutes and a lot of bandwidth on runner setup.
          pip install --no-compile --index-url https://download.pytorch.org/whl/cpu \
            -r ${{ github.workspace }}/iree-turbine//pytorch-cpu-requirements.txt
          pip install --no-compile --upgrade -r ${{ github.workspace }}/iree-turbine/requirements.txt
          pip install --no-compile -e ${{ github.workspace }}/iree-turbine/[testing,torch-cpu-nightly]
          pip install --no-compile --upgrade -r models/requirements.txt
          pip install --no-compile -e models
      
      - name: Show current free memory
        run: |
          free -mh

      - name: Run sdxl tests
        run: |
          pip install --upgrade --pre torch torchvision --index-url https://download.pytorch.org/whl/nightly/cpu
          pytest models/turbine_models/tests/sdxl_test.py --device cpu --rt_device local-task --iree_target_triple x86_64-linux-gnu
          pytest models/turbine_models/tests/sdxl_test.py --device vulkan --rt_device vulkan --iree_target_triple rdna3-unknown-linux
          pytest models/turbine_models/tests/sdxl_test.py --device rocm --rt_device rocm --iree_target_triple gfx90a
